### ISSUE TITLE
I am attempting ther same but cannot figure out the number of players

### ISSUE THREAD

**Issue by Darker** [Bzly/hunt-showdown-stat-recording#1]
Hi, I was attempting the same thing as you are with the game stats. I wanted to log stuff like how many of each monster killed, how much money I made on each day etc.

I also wanted to log the players after each match. I cannot figure out quite a few things, but most importantly there are leftover players in the XML that were not actually in the match and I don't know how to filter them out. Could you help me out please?

**Comment by bzly** [comment]
Hi @Darker! Sure. 

You can use the `Attr` element with attribute `MissionBagNumTeams` to see how many teams were in the match. The teams are numbered 0-11 (`MissionBagTeam_0` to `MissionBagTeam_11`) - 12 entries because the maximum number is 12 teams of 1 player each (in 'quick play', for example). If `MissionBagNumTeams` has a value of `4`, this means that `MissionBagTeam_0`, `MissionBagTeam_1`, `MissionBagTeam_2`, and `MissionBagTeam_3` were present in the previous mission. 

Edit: Players are identified as belonging to a specific team by the `MissionBagPlayer...` attributes, with the format `MissionBagPlayer_<team_num>_<player_num>_<attribute>`.

What I don't know is what happens to the player entries when you play a game mode where the teams aren't full. For example, if I play trios and am in `...Team0`, there will be a `MissionBagPlayer_0_0...`, a `MissionBagPlayer_0_1...`, and a `MissionBagPlayer_0_2...`. If I then go into duos, `...Team0` will have only two players in it next match, and I don't know what happens to the entries for the third player (`...Player_0_2...`). They may get removed, but I haven't verified that.

**Comment by Darker** [comment]
Thanks a lot, this is extremely helpful. I did not notice that attribute.

The players in teams are left over from previous matches - so for example if you play quickplay, there still will be 3 player teams in the file, but only the first player is valid. Each team has an attribute for player count.

**Comment by bzly** [comment]
That's alright! 

Oh yes, so there is. I've even seen that before, but forgot about it; ta 👍
